---
- name: get and install dependencies for iouyap
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - bison
    - flex
  become: yes

- name: git clone iniparser (master branch)
  git:
    repo: http://github.com/ndevilla/iniparser.git
    dest: "{{ src_dir }}/iniparser"
  register: iniparser_source

- name: make iniparser
  make:
    chdir: "{{ src_dir }}/iniparser"
  when: iniparser_source.changed

- name: copy libiniparser.a file
  copy:
    src: "{{ src_dir }}/iniparser/libiniparser.a"
    dest: /usr/lib/libiniparser.a
    remote_src: yes
  become: yes

- name: copy libiniparser.so.1 file
  copy:
    src: "{{ src_dir }}/iniparser/libiniparser.so.1"
    dest: /usr/lib/libiniparser.so.1
    remote_src: yes
  become: yes

- name: copy iniparser.h file
  copy:
    src: "{{ src_dir }}/iniparser/src/iniparser.h"
    dest: /usr/local/include/iniparser.h
    remote_src: yes
  become: yes

- name: copy dictionary.h file
  copy:
    src: "{{ src_dir }}/iniparser/src/dictionary.h"
    dest: /usr/local/include/dictionary.h
    remote_src: yes
  become: yes

- name: git clone iouyap
  git:
    repo: https://github.com/GNS3/iouyap.git
    dest: "{{ src_dir }}/iouyap"
    force: yes
  register: iouyap_source

- name: make iouyap
  make:
    chdir: "{{ src_dir }}/iouyap"
  when: iouyap_source.changed

- name: make install iouyap
  make:
    chdir: "{{ src_dir }}/iouyap"
    target: install
  become: yes
  when: iouyap_source.changed
...